# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-29 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200, verbose_name='\u516c\u4f17\u53f7\u540d\u79f0')),
                ('article_title', models.CharField(max_length=200, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('article_url', models.CharField(max_length=200, verbose_name='\u6587\u7ae0\u5730\u5740')),
                ('read', models.IntegerField(verbose_name='\u9605\u8bfb\u6b21\u6570')),
                ('like', models.IntegerField(verbose_name='\u70b9\u8d5e\u91cf')),
                ('last_edit_time', models.CharField(max_length=100, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u516c\u4f17\u53f7\u6587\u7ae0\u76d1\u63a7',
                'verbose_name_plural': '\u516c\u4f17\u53f7\u6587\u7ae0\u76d1\u63a7',
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=100, verbose_name='\u673a\u5668\u4eba\u540d\u79f0')),
                ('ip', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u5668IP')),
                ('status', models.CharField(max_length=100, verbose_name='\u5728\u7ebf\u72b6\u6001')),
                ('action', models.CharField(choices=[[b'1', '\u91cd\u542f'], [b'0', '\u9000\u51fa']], default=b'0', max_length=100, verbose_name='\u64cd\u4f5c')),
                ('account', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u5668\u5e10\u53f7')),
                ('password', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u5668\u5bc6\u7801')),
                ('login_time', models.CharField(max_length=100, verbose_name='\u767b\u5f55\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u673a\u5668\u4eba\u7ba1\u7406',
                'verbose_name_plural': '\u673a\u5668\u4eba\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=200, verbose_name='\u5fae\u4fe1\u7fa4ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='\u5fae\u4fe1\u7fa4\u540d\u79f0')),
                ('number', models.IntegerField(verbose_name='\u5fae\u4fe1\u7fa4\u4eba\u6570')),
            ],
            options={
                'verbose_name': '\u5fae\u4fe1\u7fa4\u76d1\u63a7',
                'verbose_name_plural': '\u5fae\u4fe1\u7fa4\u76d1\u63a7',
            },
        ),
        migrations.CreateModel(
            name='GroupMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=200, verbose_name='\u5fae\u4fe1\u7fa4ID')),
                ('member', models.CharField(max_length=200, verbose_name='\u5fae\u4fe1\u7fa4\u540d\u79f0')),
                ('text', models.CharField(max_length=10000, verbose_name='\u5fae\u4fe1\u7fa4\u6d88\u606f')),
                ('picture', models.ImageField(upload_to=b'Group/img/', verbose_name='\u5fae\u4fe1\u7fa4\u56fe\u7247')),
                ('recording', models.CharField(max_length=200, verbose_name='\u5f55\u97f3\u6587\u4ef6')),
                ('duration', models.IntegerField(verbose_name='\u5f55\u97f3\u65f6\u957f')),
                ('create_time', models.CharField(max_length=200, verbose_name='\u53d1\u9001\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5fae\u4fe1\u7fa4\u6d88\u606f\u76d1\u63a7',
                'verbose_name_plural': '\u5fae\u4fe1\u7fa4\u6d88\u606f\u76d1\u63a7',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=100, verbose_name='\u673a\u5668\u4eba\u540d\u79f0')),
                ('ip', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u5668IP')),
                ('log_level', models.CharField(max_length=100, verbose_name='\u65e5\u5fd7\u7b49\u7ea7')),
                ('log_msg', models.CharField(max_length=500, verbose_name='\u65e5\u5fd7\u6d88\u606f')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4ea7\u751f\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u65e5\u5fd7\u7ba1\u7406',
                'verbose_name_plural': '\u65e5\u5fd7\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_order', models.CharField(max_length=100, verbose_name='\u8ba2\u5355\u53f7')),
                ('referee', models.CharField(max_length=100, verbose_name='\u63a8\u8350\u4eba')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u7ba1\u7406',
                'verbose_name_plural': '\u8ba2\u5355\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='PushMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=600, verbose_name='\u63a8\u9001\u6d88\u606f')),
            ],
            options={
                'verbose_name': '\u63a8\u9001\u6d88\u606f',
                'verbose_name_plural': '\u63a8\u9001\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='RedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('counter', models.IntegerField(verbose_name='\u6b21\u6570')),
            ],
            options={
                'verbose_name': '\u997f\u4e86\u4e48\u7528\u6237',
                'verbose_name_plural': '\u997f\u4e86\u4e48\u7528\u6237',
            },
        ),
    ]
