# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-29 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='login_qr',
            field=models.ImageField(default=b'', upload_to=b'Robot/qr/', verbose_name='\u767b\u5f55\u4e8c\u7ef4\u7801'),
        ),
    ]
